dist: xenial
language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_script:
  - "npm install -g electron --unsafe-perm=true"
  - "npm install electron-packager -g"
  - "npm install -g electron-installer-debian"
  - "yarn"

script:
  - yarn package-win
  - yarn create-installer-win